[pytest]
minversion = 7.0
testpaths = tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*
addopts=
    -v
    --strict-markers
    --tn=short
    --disable-warnings

markers = 
    unit: testes unitários
    integration: testes de integração
    slow: testes lentos
    freecad: testes que requerem o FreeCAD em execução